# Generated by Django 2.1.5 on 2020-07-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_category_cat_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_url',
            field=models.CharField(max_length=40),
        ),
    ]
