# Generated by Django 2.1.5 on 2020-07-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200710_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(upload_to='category/'),
        ),
    ]
